osx_image: xcode9.2
language: objective-c
xcode_project: Example_Swift.xcodeproj
xcode_scheme: Example_Swift
xcode_sdk: iphonesimulator
script: ./build.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)