osx_image: xcode9.2
language: objective-c
xcode_project: Example_Swift.xcodeproj
xcode_scheme: Example_Swift
xcode_sdk: iphonesimulator
script:
  - xcodebuild -project Example_Swift.xcodeproj -scheme Example_Swift -sdk iphonesimulator build
after_success:
  - bash <(curl -s https://codecov.io/bash)