os: osx
language: objective-c
sudo: required
dist: trusty
osx_image: xcode9.2
script:
  #- eval "$(curl -sL https://raw.githubusercontent.com/DotzuX/Swift-CI/master/ci)"
  - eval "$(curl -sL https://raw.githubusercontent.com/DotzuX/Swift-CI/master/codecov)"